package ie.ucd.mscba.add.cues.deception;

import ie.ucd.mscba.add.cues.Cue;
import ie.ucd.mscba.add.cues.CueValue;
import ie.ucd.mscba.add.cues.CueValueType;
import ie.ucd.mscba.add.nlp.FeaturesExtractor;

public class CueMonetaryShorthandSymbols extends Cue {
	public CueMonetaryShorthandSymbols() {
		super("Monetary Shorthand Symbol Count", "MonetaryShorthandSymbols", "");
	}

	@Override
	public CueValue calculate(String textObservation) {
		if (textObservation == null || textObservation.isEmpty()) {
			setValue(CueValue.Default);
			return getValue();
		}

		String[] currencies = new String[] {
				"AED",
					"AFN",
					"ALL",
					"AMD",
					"ANG",
					"AOA",
					"ARS",
					"AUD",
					"AWG",
					"AZN",
					"BAM",
					"BBD",
					"BDT",
					"BGN",
					"BHD",
					"BIF",
					"BMD",
					"BND",
					"BOB",
					"BRL",
					"BSD",
					"BTN",
					"BWP",
					"BYR",
					"BZD",
					"CAD",
					"CDF",
					"CHF",
					"CLP",
					"CNY",
					"COP",
					"CRC",
					"CUC",
					"CUP",
					"CVE",
					"CZK",
					"DJF",
					"DKK",
					"DOP",
					"DZD",
					"EGP",
					"ERN",
					"ETB",
					"EUR",
					"FJD",
					"FKP",
					"GBP",
					"GEL",
					"GGP",
					"GHS",
					"GIP",
					"GMD",
					"GNF",
					"GTQ",
					"GYD",
					"HKD",
					"HNL",
					"HRK",
					"HTG",
					"HUF",
					"IDR",
					"ILS",
					"IMP",
					"INR",
					"IQD",
					"IRR",
					"ISK",
					"JEP",
					"JMD",
					"JOD",
					"JPY",
					"KES",
					"KGS",
					"KHR",
					"KMF",
					"KPW",
					"KRW",
					"KWD",
					"KYD",
					"KZT",
					"LAK",
					"LBP",
					"LKR",
					"LRD",
					"LSL",
					"LYD",
					"MAD",
					"MDL",
					"MGA",
					"MKD",
					"MMK",
					"MNT",
					"MOP",
					"MRO",
					"MUR",
					"MVR",
					"MWK",
					"MXN",
					"MYR",
					"MZN",
					"NAD",
					"NGN",
					"NIO",
					"NOK",
					"NPR",
					"NZD",
					"OMR",
					"PAB",
					"PEN",
					"PGK",
					"PHP",
					"PKR",
					"PLN",
					"PYG",
					"QAR",
					"RON",
					"RSD",
					"RUB",
					"RWF",
					"SAR",
					"SBD",
					"SCR",
					"SDG",
					"SEK",
					"SGD",
					"SHP",
					"SLL",
					"SOS",
					"SPL",
					"SRD",
					"STD",
					"SVC",
					"SYP",
					"SZL",
					"THB",
					"TJS",
					"TMT",
					"TND",
					"TOP",
					"TRY",
					"TTD",
					"TVD",
					"TWD",
					"TZS",
					"UAH",
					"UGX",
					"USD",
					"UYU",
					"UZS",
					"VEF",
					"VND",
					"VUV",
					"WST",
					"XAF",
					"XCD",
					"XDR",
					"XOF",
					"XPF",
					"YER",
					"ZAR",
					"ZMW",
					"ZWD"
		};
	
		double currencyCount = 0.0; 
		String[] tokens = FeaturesExtractor.getTokens(textObservation);
		for (String token : tokens) {
			for (String currency : currencies) {
				if (token.equalsIgnoreCase(currency)) {
					currencyCount++;
				}
			}
		}

		setValue(new CueValue(CueValueType.Real, currencyCount));
		return getValue();
	}
}
