package ie.ucd.mscba.add.cues.deception;

public enum CuesTypes {
	UNKNOWN,
			
	STATEMENTS_COUNT,
	WORDS_COUNT,
	SYMBOLS_COUNT,
	NUMBERS_COUNT,
	DIGITS_COUNT,
	MONETARYSYMBOLS_COUNT,
	MONETARYSHORTHANDSYMBOLS_COUNT,
	MEASUREMENTS_COUNT,
	SYLLABLES_COUNT,
	COMPLEXWORDS_COUNT,
	WRONGWORDS_COUNT,
	
	AVGWORDSLENGTH,
	AVGSTATEMENTLENGTH,
	
	SMOGREADABILITY_READABILITYINDEX,
	SMOGREADABILITY,
	GUNNINGFOG_READABILITYINDEX,
	FLESCHREADABILITY_READABILITYINDEX,
	FLESCHKINCAIDREADABILITY_READABILITYINDEX,
	COLEMANLIAU_READABILITYINDEX,
	AUTOMATEDREADABILITY_READABILITYINDEX,
}
